version: '3'
services:
  country-service:
    image: countries-assembly:1.0.1
    ports:
      - "8081:8080"

  airport-service:
    image: airport-assembly:1.0.1
    ports:
      - "8082:8080"
  nginx:
    image: custom-nginx:latest
    ports:
      - "8000:8000"
    links:
      - country-service
      - airport-service
